import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";  // Import de la navbar
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar fixée en haut */}
        <Navbar />
        {/* Compense la hauteur de la navbar avec un padding-top pour éviter le chevauchement */}
        <div className="pt-[70px]"> {/* Ajustez la valeur en fonction de la hauteur de votre navbar */}
          {children}
        </div>
      </body>
    </html>
  );
}

